### ISSUE TITLE
Imperial temps show in C

### ISSUE THREAD

**Issue by stevenrt** [willasm/obsidian-open-weather#11]
Thanks for the plugin.  I just installed it and noticed that when I set it to report in imperial that it reflects the temperature with a "C" suffix instead of a "F" suffix in the status bar.  So, it is currently 44 F where I live.  Your plugin reports the temp as 44 C.

**Comment by willasm** [comment]
That is an easy fix, just go to the plugins settings and and edit the `Weather String Format Statusbar`. The default is...

' | %desc% | Current Temp: %temp%°C | Feels Like: %feels%°C | '

Just change the two 'C' to 'F'
