### ISSUE TITLE
Error when set Location

### ISSUE THREAD

**Issue by mateusfg7** [willasm/obsidian-open-weather#14]
I'm receiving this error for every character I write to "Enter Location" input:

![image](https://github.com/willasm/obsidian-open-weather/assets/40613276/6140d043-b3f6-4745-91b8-92b664dcfe7c)

**Comment by willasm** [comment]
Thanks for the descriptive report and this should be an easy fix. Unfortunately my dev pc died on me so I cannot do any work on it until I finish my new pc build (hopefully that will be done in a week from now). Note that once you complete entering a valid location, the pop up messages will stop and the plugin will work as it should. Will fix this as soon as my new pc is build is completed. Thanks for your patience.

**Comment by mateusfg7** [comment]
Yes, everything seems to work well, it is just an annoying message.

**Comment by geezbert** [comment]
I get the same Error Code, doesn't work for me unfortunately.

**Comment by willasm** [comment]
Sorry for the late reply but I just finished my new pc build last week. Being retired and on a tight budget, I just could not afford to complete the new build until recently. Hoping to have this fixed this week. Just need a couple of days to refresh myself with where I left off the last time I worked on this. Will update this post when it is completed.

**Comment by willasm** [comment]
The fix has been uploaded as v1.6.0 and should be available in Obsidian shortly. Did not take as long as I thought it would.

Thanks for your patience, William.

**Comment by willasm** [comment]
The next release which is coming soon now returns an error message on any errors.
This was related to this issue as the notifications were being used for errors.
The returned weather string will be `Error Code 404: city not found` or other messages on any error getting the weather data.
Closing this as completed.
