### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by joethei** [willasm/obsidian-open-weather#20]
Hi @willasm 

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason:
- No release found for version 1.7.0

We will remove this plugin from the community plugins if this issue is not fixed within 30 days.

- The Obsidian Team

**Comment by willasm** [comment]
I was about to create new release then found a bug that needed to be fixed. All corrected now and new release has been created.

Thanks, William.
