### ISSUE TITLE
Weather string not returning data

### ISSUE THREAD

**Issue by mituller** [willasm/obsidian-open-weather#21]
I am attempting to add weather to a template and in following the documentation, I would think this would return the current weather. 

%weather1%

The weather string is returned as a text string. I know OpenWeather is working as I have it displaying in the statusbar and it is correct. Also, if I run the command "OpenWeather: Replace template string" it will change to the right weather. From what I understand if I have  %weather1% in the template and add it to a new file, it would display the weather. Is there something that I am doing or are my expectations wrong? Shouldn't it automatically convert?

**Comment by willasm** [comment]
It only automatically converts it when creating a new note from a template. If inserting into an existing you will need to run the command `OpenWeather: Replace template string` to have it replaced with the current weather. Obsidian itself does not have a command built in to create a new note from a template. You would need to use the templater plugin to do that. This is interesting as you are the first person to ask this with over 6k downloads for the plugin. I will look into this and see if it is even possible to watch for the insert template command being run. If I can catch the event for the command I could then convert it to the weather string. To be honest with you I assumed everyone would be using this with templater templates, but I should have considered using it like this.

Once again, I'll look into this and see if it is possible, William.

**Comment by willasm** [comment]
I should have also mentioned that if you just want to insert it into the current document you can use the command `OpenWeather: Insert weather string one` which will insert the current weather format of the first string defined in the settings.

**Comment by mituller** [comment]
Thanks. I'm just starting with Obsidian so was confusing. I will look at creating a new note from a template.

**Comment by willasm** [comment]
That makes sense. I do suggest playing around with the built in core plugin templates until you get a good understanding of how they work, then add the `templater` plugin. It offers a lot more options than the core template plugin does and it is one of the most popular plugins used in Obsidian.

**Comment by mituller** [comment]
Thank you for your help.

**Comment by willasm** [comment]
I am going to close this issue but feel free to re-open it or create another if you have any questions or problems you need help with.
