### ISSUE TITLE
Freezing & crashing when opening settings

### ISSUE THREAD

**Issue by stark1tty** [willasm/obsidian-open-weather#22]
Hey, I am having some trouble with this extension. I really want to use it, but cannot enter the settings lest Obsidian seizes and crashes. Is there a way to turn on logging to get you a report? :)

**Comment by willasm** [comment]
Can you open the developers console ctrl+shift+i before entering settings? If so do you see any error messages there? Is this a new install of the plugin or have you been using it already? I recently updated the plugin with a lot of new changes so it is always possible there might be a bug. What version of Obsidian do you have as well as it was updated not long ago.

**Comment by willasm** [comment]
I have tried to re-produce this with several different vaults. One with 44 other plugins down to a newly created vault with no other plugins or themes at all and I am not seeing any problems. I'm curious to know, do you have any plugins that are specifically for enhancing or changing the settings layout in any way? There are a couple that I can see in a search for settings in the plugins tab, Settings profiles, and Settings search being a couple of them. I really would like to know what is causing this. Any info you can provide would be helpful including your OS version and Obsidian version.

**Comment by willasm** [comment]
I have to close this unless you can give me more details. I have tried many combinations to re-produce this but I can not get this behavior to happen. If you can provide more info feel free to re-open this or create another issue. I would like to know if my plugin is causing this issue for you but I think it must be something else as no one else has reported anything like this happening.
