### ISSUE TITLE
Feature request - Retrieve weather data from a different day than today

### ISSUE THREAD

**Issue by Lorite** [willasm/obsidian-open-weather#24]
Hi, thanks a lot for your plugin. It works great!

Sometimes, when I don't have access to my laptop, I take daily notes on a fleeting note and then create a proper daily note. On my daily notes, I use your plugin to retrieve the weather. It would be great if the plugin would check for the file name to see if it matches "YYYY-MM-DD" or whatever format you specify in the plugin's settings.

Let me know if you need any help implementing it. Maybe I can help if I find some spare time :)

Thank you!!!

**Comment by willasm** [comment]
Sorry for not getting back to you sooner, been very busy lately. I'm not exactly sure what it is you are doing? Are you saying you create notes by some other method, then create your daily note in Obsidian at another time in the future (next day for example) and you need the weather from a previous day? If you want the weather from a previous day that will not work. The API only returns only the current weather, historical weather requires a paid API. I do have an update to upload that allows getting the 5 day forecast weather which would help for future dates but historical data would be a problem. If I am misunderstanding you and it is something else you are trying to accomplish, please let me know.

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

@Lorite This would actually be doable with the new plugin although I would need to think about how to approach this. Each day requested for historical data has a query cost and if that goes over the 1000 points they give you daily you would not be able to get any more data until the next day. This will at any rate have to wait until the new plugin is completed and published as that is the main priority at the moment.

Thank you, William McKeever
