### ISSUE TITLE
Feature Request: Support for Lucide Icons

### ISSUE THREAD

**Issue by angiioh** [willasm/obsidian-open-weather#27]
Since Obsidian uses Lucide icons, I thought it would be neat if there was a variant of %icon% that could use the Lucide weather icons.

**Comment by willasm** [comment]
Sorry for the late reply but for some reason I never got a notification for this post? I only just saw this after getting a different notification today. I will have a look at the Lucide icons and see if they have enough to coincide with all the possible weather conditions. I will be uploading an update this weekend so I will look into this as soon as that is done.

**Comment by angiioh** [comment]
No worries! Thanks for looking into it :]

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

@angiioh I did look into this and while it could be doable it would actually be a lot of work and time consuming to find a matching icon for every possible weather condition. I may actually do this however with the new plugin as the default ones they provide are not all that appealing. Getting the new plugin finished and then published has to take all priority for now though.

Thank you, William McKeever
