### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Accelsnow** [willasm/obsidian-open-weather#31]
In the current README under [Weather String Placeholders - Current Weather Placeholders](https://github.com/willasm/obsidian-open-weather?tab=readme-ov-file#current-weather-placeholders), it seems like `date1` and `date2` are flipped: `date1` may display single digit day while `date2` zero-prepends single digit days. The observed behavior is consistent with the naming of `year1`, `year2` and `month1`, `month2`, so I think it might have been a typo.

Obsidian: v1.6.5
Plugin: v1.8.0

**Comment by willasm** [comment]
Sorry for not getting back to you sooner. I was busy completing 2 new VSCode extensions but I am free to work on this one again. I'm sure you are correct and that is just a typo. I will correct that as soon as I fix a minor bug that another user found. Should be updated soon.

Thanks for bringing this to my attention, William.

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

Thank you, William McKeever
