### ISSUE TITLE
Min and Max temperature is bugged

### ISSUE THREAD

**Issue by TheBrightSoul** [willasm/obsidian-open-weather#32]
As you can see in the image It's not giving proper min and max temperature
![image](https://github.com/user-attachments/assets/e3ca34ce-4a38-4c9e-b856-6e5e4454426e)
![image](https://github.com/user-attachments/assets/a91d2889-3dc2-4c97-a07a-3d3086c79582)
And I've also provided the corresponding string

**Comment by willasm** [comment]
That is actually what the API returns. It is only the min/max for the current 3 hour block of weather data, not for the entire day. It will rarely have more than a degree or 2 difference. To be honest with you I very nearly left it out all together as it really isn't all that useful most of the time. To get the daily high and low I would need all the data for the entire day and that is only possible if the plugin is launched around midnight. The API does not return the data from an earlier time, just the current time and forward so there is no way to get the lowest and highest temps for the entire day except around midnight. It is unfortunate, but that is how it works.

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

@TheBrightSoul The API used by the new plugin does not suffer from this. It actually returns the daily high and low temperature for 15 days in a useable form. That was one of my biggest problems with the Open Weather API.

Thank you, William McKeever
