### ISSUE TITLE
Changing the latitude and longitude fileds directly in the data.json file has no effect

### ISSUE THREAD

**Issue by jamaroo** [willasm/obsidian-open-weather#34]
I want to change the values automatically by having a script that takes new coordinate values for each of location note I have, however it seems this has no effect. It only works if I input these values manually in the prompt boxes. How can I fix this? Thanks

**Comment by willasm** [comment]
You most likely have the current location set which overrides the latitude and longitude settings when it exists. Try clearing the setting for your city's name. From your description of what you are trying to accomplish though, this won't work as the plugin only handles one location. After each change the plugin would need to be reloaded and the previous location would be lost. One other person has requested having more than one location so I will look into this again. The biggest issue is sending to many requests to quickly to the API. There is a limit on how many requests can be sent per second, minute, etc. and I would have to send a request for each location. If the plugin goes over the limit, then the API will not return any data.

How many locations are you wanting to use? I could always add a delay between each request but with a large number of locations, that would likely cause other issues.

Thanks, William.

**Comment by willasm** [comment]
I just want to inform everyone that this plugin in being discontinued. Open Weather has discontinued the API 2.5 on which this plugin is based. I have however created a new plugin using the Visual Crossing Weather API and it follows the same basic approach to representing the weather as this plugin did so it should be relatively easy to move over to the new plugin. While it is still in development it is almost 100% functional. The documentation however is almost non existent but the list of available macros is complete and is in a nicely formatted table for better viewing. I hope to have it published soon as it is very close to being completed. If you want to try it before it is released you can find it on Github [here](https://github.com/willasm/vc-weather).

@JoaoAmaro2001 The new plugin now supports up to 5 locations which I believe would solve your issue.

Thank you, William McKeever
