### ISSUE TITLE
Can we consider using Emoji in the status bar to represent the weather?

### ISSUE THREAD

**Issue by kickTiger** [willasm/obsidian-open-weather#5]
Can we consider using Emoji in the status bar to represent the weather?

the following are Emoji symbols representing weather:

Sunny: ☀️, 🌞, 🔆
Cloudy: ☁️, ⛅, 🌥️
Partly cloudy: 🌥️
Rainy: 🌧️, ⛈️, 🌦️, ☔
Snowy: 🌨️, ❄️, ⛄, ☃️
Tornado: 🌪️
Typhoon: 🌀
Rainbow: 🌈
Foggy: 🌫️
Windy: 🌬️
Thermometer: 🌡️
Some symbols have slight differences:

☀️ represents a completely cloudless sun.
🌞 represents a smiling sun.
🔆 represents a high brightness button and can be used to represent intense sunlight.
☁️ represents a cloud and can be used to represent cloudy or overcast weather.
⛅ represents a sun partially covered by clouds.
🌥️ represents a sun partially covered by clouds, and can be used to represent partly cloudy weather.
🌧️ represents rain, with raindrops falling from a cloud.
⛈️ represents a cloud with lightning and rain.
🌦️ represents changing weather from sunny to rainy or vice versa.
☔ represents an umbrella and can be used to represent rainy weather.
🌨️ represents snowfall, with snowflakes falling from a cloud.
❄️ represents a single snowflake.
⛄ represents a snowman.
☃️ represents a snowman and snowflakes.
🌪️ represents a tornado and can be used to represent extreme weather conditions such as storms.
🌀 represents a typhoon or vortex shape and can also be used to represent dizziness.

**Comment by willasm** [comment]
Great suggestion. I will be adding this option soon. Thanks for the list also, that is very helpful.

**Comment by willasm** [comment]
Done. Added in release v1.5.0
To use just add `%desc-em%` into your statusbar text and it will be replaced with the corresponding emoji.
I tried to match emojis as close to the actual conditions as possible although there are no emojis for a couple of the possible conditions.
In those cases I just used the closest available emoji.

## [1.5.0] 2022-03-18
### Added
- Weather Description Emojis
  - Macro `%desc-em%` will be replaced with an emoji of the current weather description
