### ISSUE TITLE
Would it be possible to consider adding support for multiple languages?

### ISSUE THREAD

**Issue by kickTiger** [willasm/obsidian-open-weather#6]
I have modified the display of the status bar to the corresponding language by performing the following steps:

1.Open the main.js file located in .obsidian\plugins\open-weather, and find the following code at around line 55:
```js
let url = https://api.openweathermap.org/data/2.5/weather?q=${this.location}&lang=zh_cn&appid=${this.key}&units=${this.units};
```

2.Add `&lang=zh_cn` before` &appid`, and the status bar at the bottom will display in the corresponding language.

### Suggestions:

You may want to consider adding a drop-down menu to the plugin's settings, giving users the option to display the weather information in their preferred language.

Currently, my modification only enables the status bar to appear in the selected language. I would like to suggest expanding this feature to also support the display of weather information in the chosen language.

### Reference materials: 
After reviewing the official documentation, it appears that the supported languages may include the following:"

```js
&lang=zh_cn (Chinese Simplified) 
&lang=en (English) 
&lang=ru (Russian) 
&lang=it (Italian) 
&lang=es (Spanish) 
&lang=uk (Ukrainian) 
&lang=de (German) 
&lang=pt (Portuguese) 
&lang=ro (Romanian) 
&lang=pl (Polish) 
&lang=fi (Finnish) 
&lang=nl (Dutch) 
&lang=fr (French) 
&lang=bg (Bulgarian) 
&lang=sv (Swedish) 
&lang=zh_tw (Chinese Traditional) 
&lang=tr (Turkish) 
&lang=hr (Croatian) 
&lang=ca (Catalan)
&lang=ar (Arabic) 
&lang=cz(Czech) 
&lang =el(Greek) 
& lang =fa(Persian) 
& lang =gl(Galician) 
& lang =hu(Hungarian) 
& lang =ja(Japanese) 
& lang =kr(Korean)
```

**Comment by willasm** [comment]
Thanks again for another great suggestion. This will be added for sure. Should have this added this weekend.

**Comment by willasm** [comment]
Done. Languages are supported in release v1.4.0 which should be available shortly.

## [1.4.0] 2022-03-18
### Added
- Language support for the following languages
  - af - Afrikaans
  - al - Albanian
  - ar - Arabic
  - az - Azerbaijani
  - bg - Bulgarian
  - ca - Catalan
  - cz - Czech
  - da - Danish
  - de - German
  - el - Greek
  - en - English
  - eu - Basque
  - fa - Persian (Farsi)
  - fi - Finnish
  - fr - French
  - gl - Galician
  - he - Hebrew
  - hi - Hindi
  - hr - Croatian
  - hu - Hungarian
  - id - Indonesian
  - it - Italian
  - ja - Japanese
  - kr - Korean
  - la - Latvian
  - lt - Lithuanian
  - mk - Macedonian
  - no - Norwegian
  - nl - Dutch
  - pl - Polish
  - pt - Portuguese
  - pt_br - Português Brasil
  - ro - Romanian
  - ru - Russian
  - sv - Swedish
  - sk - Slovak
  - sl - Slovenian
  - sp - Spanish
  - sr - Serbian
  - th - Thai
  - tr - Turkish
  - ua - uk Ukrainian
  - vi - Vietnamese
  - zh_cn - Chinese Simplified
  - zh_tw - Chinese Traditional
  - zu - Zulu
