### ISSUE TITLE
Feature suggestion to insert static text of weather when calling template plugins

### ISSUE THREAD

**Issue by kickTiger** [willasm/obsidian-open-weather#9]
I want to include weather information as static text in my diary, which was created using a template plugin. 

The plugin currently uses dynamic syntax like "<% tp.date.now("YYYY-MM-DD", 0)%>" to display the current date, but it doesn't support dynamic weather data.

Therefore, I'm wondering if it would be possible to introduce a new syntax that allows me to add static weather text to the generated template.

**Comment by willasm** [comment]
That ability already exists, just add the following to your templates for static weather...

You can place the following strings in your templates and when creating a new document using the template, they will automatically be replaced with the corresponding weather strings.

- `%weather1%` - Inserts weather string format One
- `%weather2%` - Inserts weather string format Two
- `%weather3%` - Inserts weather string format Three
- `%weather4%` - Inserts weather string format Four

You can customize the weather string formats in the plugins settings.

If want dynamic weather in your templates that is a bit more involved. Have a look at the  file `EXAMPLE.md` for details.

**Comment by kickTiger** [comment]
Thank you so much for your reply. Please forgive my carelessness for not reading the document carefully. This is an excellent plugin, and I have already recommended it on my blog

**Comment by willasm** [comment]
Thank you very much, have a great day.
